spring.application.name=Backend

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://user:dbuser1234@uniops.i8haija.mongodb.net/CampusOperationsHub?retryWrites=true&w=majority&appName=UniOps

# Server port
server.port=8085

# Google OAuth - put your actual values directly here
spring.security.oauth2.client.registration.google.client-id=722391233851-aaqogprb9v4r2ee7oekl5dgficfqp2gn.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8085/login/oauth2/code/google

# Redirect back to React
app.oauth2.redirect-uri=http://localhost:3000/oauth/callback